name: CMake

on:
  push:
    branches: [ "main", "feature/**"]
  pull_request:
    branches: [ "main", "feature/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ninja
      run: apt-get install -y ninja-build

    - name: Setup Ninja
      run: apt-get install -y ninja-build

    - name: Configure CMake
      run: cmake ${{github.workspace}} --preset=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build

